listaLitere(
    [hol,biblioteca,cameraE,
    cameraES,cameraEE,debara,bucatarie,
    cameraNW,cameraW,cameraWW,cameraWS,cameraNE]).
listaLanterna(
    [hol,biblioteca,cameraE,cameraES,
    cameraEE,debara,bucatarie,cameraNW]).
listaComestibile(
    [hol,biblioteca,cameraE,cameraES,
    cameraEE,debara,bucatarie,cameraNW,cameraW,
    cameraWW,cameraWS,cameraNE,cameraCapcana2,cameraCapcana1]).


alegeCamera(L,Locatie):-
    length(L,X),
    random(0,X,Pozitie),
    nth0(Pozitie,L,Locatie),!.


distribuieObiecte():-
        listaLitere(L1),
        listaLanterna(L2),
        listaComestibile(L3),
        alegeCamera(L1,R1),
        retract(locatieObiect(scrisoareLitera1,_)),
        assert(locatieObiect(scrisoareLitera1,R1)),
        alegeCamera(L1,R2),
        retract(locatieObiect(ghicitoare,_)),
        assert(locatieObiect(ghicitoare,R2)),
        alegeCamera(L1,R3),
        retract(locatieObiect(carteLitera2,_)),
        assert(locatieObiect(carteLitera2,R3)),
        alegeCamera(L1,R4),
        retract(locatieObiect(bilet,_)),
        assert(locatieObiect(bilet,R4)),
        alegeCamera(L2,R5),
        retract(locatieObiect(lanterna,_)),
        assert(locatieObiect(lanterna,R5)),
        alegeCamera(L3,R6),
        retract(locatieObiect(mar,_)),
        assert(locatieObiect(mar,R6)),
        alegeCamera(L3,R7),
        retract(locatieObiect(biscuit,_)),
        assert(locatieObiect(biscuit,R7)),
        alegeCamera(L1,R8),
        retract(locatieObiect(scrisoareLitera5,_)),
        assert(locatieObiect(scrisoareLitera5,R8)),
        alegeCamera(L1,R9),
        retract(locatieObiect(carteLitera4,_)),
        assert(locatieObiect(carteLitera4,R9)),!.